# Generated by Django 4.1.7 on 2023-02-20 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Date',
            field=models.DateField(default='1992-02-11'),
            preserve_default=False,
        ),
    ]
